# Generated by Django 4.2.1 on 2023-07-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
